jwt:
  secret-key: 0PhlIGkud4FTrX4ZFvsgjwbgHXXj1QsznpS3jOKq4cw=

oauth:
  kakao:
    client-id: 0ca68ddfc2aad4585b3d69b49b803298
    redirect-uri: https://ochaelwan.vercel.app/kakao/callback
    authorization-grant-type: authorization_code
    client-authentication-method: POST
    client-name: Kakao
    scope:
      - profile_image
      - profile_nickname
      - account_email
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com


# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://projectdb.cxsk26s8kxis.ap-northeast-2.rds.amazonaws.com:3306/tccdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: root1234
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true


  # spring data jpa 설정
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false